configs:
  ssh:
    extraHosts: |-
      git.core.infra.home ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFQ/sa0z3k+szvsagM6tgbA/cvYXmQ3ntBMFd292fueb
      git.core.infra.home ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDin3MA4RA3sNqzjrTB2pnGn9KmRyuvDushDSfbOcIJoRhoeq/3HGrUw0z0cTeVCV0xODvlnHC9aofo8jzzSiBOvcSL5u1A4pRIJnMlorVDVecIC2Rk90HYktOIH5T5Ve6475fX8WOLYyLlA26n4wRnQYpOx0RCZflyVLl2Yin3DE/CATvs6879nKHwq8K5sW7lvHGVlD5B8t3TIaiGyPuq1UfeDkSw0SdSKvL+izhYCToV0D/G68ZsLuTov9MXZGPq1oZNyqzyGi4fMwEW9kKB7HbROBMkbGe/EGl1+NVoZxCxGBEqZce+MQ6OPM///yNMa8oR3Euvj0g0iidjqPI6Z64EFNZZnhDbpjUDAXLdsbdx0E7prPllaUsu4wc3dk3cK8njMV6UXxs5NJMvW6N7kNhyNu995heagD8+1wIZ2u1gXAD/ycnkcbRJCCQrWcAlB8B7jPgZ6TG01xlLFTG26FUexnpgZFTzRN8IXi8g+EyP9aA1S2AnEX455PqUNqXUPM0e1qJYR6mpV3yoVa4peWnGGgQw1nyvlwZAmIp0HfI71uXP9mWDWITWI39847Jpehyzrr0IWS6Eft2GvgpF4hS+tJzHn6D7B8/473P65WQew7NaH7zu+7z59102UwKukbzxKaryfRX572JQdkGezXtZWZtmLZ+JEIl2fi18zQ==    
  tls:
    certificates:
      git.core.infra.home: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRALyACDqvY5L1xzepkv9MAmowCgYIKoZIzj0EAwIwKDEO
        MAwGA1UEChMFU3dpZ2cxFjAUBgNVBAMTDVN3aWdnIFJvb3QgQ0EwHhcNMjYwNzA3
        MTgxODA2WhcNMzYwNzA0MTgxODA2WjAoMQ4wDAYDVQQKEwVTd2lnZzEWMBQGA1UE
        AxMNU3dpZ2cgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGYGzlTA
        hEx2z0kX44iDOKhd3EMrZWV0nutokd7yaG+pdblaVDvKiCgXINJ+pTn2XsSdnKFM
        vTucrMmGGk6PIwejRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBRKbdW7QSdIlpMsBBmw0FqZvaf1lDAKBggqhkjOPQQDAgNI
        ADBFAiAJ8vKh66nbAMngH4q7aamLdg0gUIrvg8q4EGeatPWTswIhAMcpobQza5yd
        CKRCnLkdxVryQbMGzxHi2QaxVX2G3ETb
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIBvTCCAWOgAwIBAgIRAK8FTBsB+mAo+4rNNX8ubqIwCgYIKoZIzj0EAwIwKDEO
        MAwGA1UEChMFU3dpZ2cxFjAUBgNVBAMTDVN3aWdnIFJvb3QgQ0EwHhcNMjYwNzA3
        MTgxODA3WhcNMzYwNzA0MTgxODA3WjAwMQ4wDAYDVQQKEwVTd2lnZzEeMBwGA1UE
        AxMVU3dpZ2cgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
        QgAE0ueAp4Ul8fwD9H5WPG2MwVW9P3mM1S/wgZlpLMRiCYR2M+o/8RXoKH7uzeBs
        xJDDSA7pLq7iK/pfT8dX0lYkRaNmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB
        /wQIMAYBAf8CAQAwHQYDVR0OBBYEFHEQtllpRIHVyFScY+P6rZxyUOF5MB8GA1Ud
        IwQYMBaAFEpt1btBJ0iWkywEGbDQWpm9p/WUMAoGCCqGSM49BAMCA0gAMEUCIB1z
        qRxSYRLBtMrX6o9gyQOtxSxa4M8zF1brF5pHWBAkAiEA9isNhjkV6Lkv507coG6L
        8sLCPc3EmMAVqHGzaDj0tRw=
        -----END CERTIFICATE-----
