apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: openebs
  namespace: openebs
  includeCRDs: true
  releaseName: openebs
  version: 4.6.0
  repo: https://openebs.github.io/openebs
  additionalValuesFiles:
  - values.additional.yaml
